server.port=9081

#server.servlet.context-path=/mas/

#Reporting path .92
rpt.repository.path = C:\\Users\\User\\Documents\\Reports\\


x#spring.datasource.url=jdbc:postgresql://localhost:5432/instChangesDB
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto = update

#server.servlet.context-path=/mas/

spring.datasource.url=jdbc:oracle:thin:@//10.17.1.73:1522/ORCL19C.LOCALDOMAIN.com?useUnicode=yes&characterencoding=utf-8&charactersetresults=utf-8
spring.datasource.username=MASPRIME_POST_PROD
spring.datasource.password=MASPRIME_POST_PROD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.driver-class-name=oracle.ojdbc.OracleDriver

#Switch connection
switchdb.datasource.url=jdbc:oracle:thin:@10.17.1.73:1522:ORCL19C?useUnicode=yes&characterencoding=utf-8&charactersetresults=utf-8
switchdb.datasource.username=ISTSIT_APP
switchdb.datasource.password=istsit
switchdb.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.datasource.url=jdbc:oracle:thin:@172.18.11.9:1521/DBTESTMDSL?useUnicode=yes&characterencoding=utf-8&charactersetresults=utf-8
#spring.datasource.username=MASPRIME100
#spring.datasource.password=Pa$$w0rd12345678
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.driver-class-name=oracle.ojdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.connection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.output.ansi.enabled=always

#server.tomcat.uri-encoding=UTF-8



# HTTP encoding (HttpEncodingProperties)
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true

jwt.secret=mdsl
jwt.expirationMs=86400000
jwt.refreshExpirationMs=432000000

#appVersion=/v1
#appId=1

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mvc.log-request-details=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

default.UserRole=Administrator

default.AdminRole=Administrator


#spring.mail.host=smtp.office365.com
#spring.mail.port=587
#spring.mail.username=testsmtp@taly.com.eg
#spring.mail.password=Taly@2023N
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
# Mailtrap SMTP Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=78839e0a381ff1
spring.mail.password=825b8e922f0364
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
email.template.base-path=C:/mas/
