package com.mdsl.utils.enumerations;

import lombok.Getter;

@Getter
public enum FileLayoutElementEnum {
	CARD_NUMBER("CARD_NUMBER"),
	MASK_CARD_NUMBER("MASK_CARD_NUMBER"),
	ACCOUNT_NUMBER("ACCOUNT_NB"),
	CUSTOMER_NUMBER("CUSTOMER_NUMBER"),
	AMOUNT("AMOUNT"),
	SET_CODE("SET_CODE"),
	TRANSACTION_ID("TRANSACTION_ID"),
	SETTLMENT_CYCLE_ID("SETTLMENT_CYCLE_ID"),
	CURRENCY_CODE("CURRENCY_CODE"),
	CREATED_DATE("CREATED_DATE"),
	CREATED_TIME("CREATED_TIME"),
	TRANSACTION_TYPE("TRANSACTION_TYPE"),
	AUTH_CODE("AUTH_CODE"),
	ERROR_CODE("ERROR_CODE"),
	ERROR_DESC("ERROR_DESC"),
	TXN_DESC("TXN_DESC"),
	REASON("REASON"),
	SYSTEM_DATE("SYSTEM_DATE"),
	CIRCUMFLEX("CIRCUMFLEX"), 
	COMMA("COMMA"),
	DASH("DASH"),
	PERCENTAGE("PERCENTAGE"), 
	QUESTION("QUESTION"),
	SEMI_COLON("SEMI_COLON"),
	SPACE("SPACE"),
	FILLER("FILLER");
	
	private final String code;

	FileLayoutElementEnum(String statusCode) {
		this.code = statusCode;
	}
}