package com.mdsl.model.dto.response;

import java.sql.Timestamp;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class TransactionCurrentSearchResponseDto {
    private Integer recordSeqId;
    private String institutionId;
    private String outletCode;
    private String merchantName;
    private String merchantCategory;
    private String merchantBank;
    private String merchantAccountNumber;
    private String merchantIBAN;
    private String merchantAccountCurrency;
    private String merchantBranch;
    private String merchantBankSwift;
    private String merchantBeneficiaryName;
    private Timestamp merchPaymentDate;
    private String terminalId;
    private String terminalLocation;
    private String sourceReference;
    private String pan;
    private String cardNumber;
    private String maskPan;
    private Integer cardSeqNumber;
    private Timestamp expiryDate;
    private String microfilmRefNumber;
    private Integer refNumberSeq;
    private String issuerAcqProfile;
    private String cardScheme;
    private String linkupCode;
    private Integer processingCode;
    private String transId;
    private String reversalFlag;
    private Double sourceAmount;
    private String sourceCurrency;
    private Double billingAmount;
    private String billingCurrency;
    private Double settlementAmount;
    private String settlementCurrency;
    private Double localAmount;
    private String localCurrency;
    private Double tipsAmount;
    private Double tipsSettlementAmount;
    private String tipsCurrency;
    private Double dccAmount;
    private String dccCurrency;
    private Double dccMerchantAmount;
    private Double dccMerchantSettlementAmount;
    private String dccMerchantSettlementCurrency;
    private Double merchantCommission;
    private Double merchMarkup;
    private Double chMarkup;
    private Double feeAmount1;
    private String feeAmount1Currency;
    private Double feeAmount2;
    private String feeAmount2Currency;
    private Double transactionAmount;
    private String transCurrency;
    private Timestamp transactionDate;
    private Timestamp transTime;
    private String authorizationNumber;
    private Character billingProcessingFlag;
    private Character settlProcessingFlag;
    private Integer settlProcessingNumber;
    private Character settlMerchHalt;
    private String batchId;
    private String merchantCountry;
    private String acquirerId;
    private String issuerId;
    private String issuerRefNumber;
    private String acqInstId;
    private String issuerInstId;
    private String acquirerData;
    private String issuerData;
    private String terminalData;
    private Character ecommerceFlag;
    private String originNetwork;
    private String destinationNetwork;
    private Timestamp processingDate;
    private String merchSettlementDate;
    private String reversalReason;
    private String reversalComment;
    private Character manualEntry;
    private String manualComment;
    private String chargebackComment;
    private String chargebackReason;
    private String representmentComment;
    private String representmentReason;
    private Character confirmStoppingPayment;
    private Character toBePaidToMerchant;
    private String payHaltComment;
    private String payHaltStatus;
    private Integer usageCode;
    private Integer reasonCode;
    private Character acquirerRecordToAppear;
    private Character issuerRecordToAppear;
    private String processingRefNumber1;
    private String processingRefNumber2;
    private String processingRefNumber3;
    private String processingRefNumber4;
    private String processingRefNumber5;
    private String userCreate;
    private Timestamp dateCreate;
}
